USE sw;
DROP TABLE IF EXISTS TASK_INDEX;  
CREATE TABLE TASK_INDEX (  
  TASK_NAME varchar(20) NOT NULL,  
  TASK_CATE int(1),  
  IP_TYPE int(1),  
  DOWNLOAD_ADDRESS varchar(100),  
  IS_VALID int(1),  
  PRIMARY KEY (TASK_NAME)  
)  DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS TASK_VS_BACKGROUND;  
CREATE TABLE TASK_VS_BACKGROUND (  
  TASK_NAME varchar(20) NOT NULL,  
  BACKGROUND_NO varchar(5) NOT NULL,  
  QUANTITY_REQUIRE decimal(10),  
  QUANTITY_FINISHED decimal(10),  
  ID_ACTIVE int(5), 
  ID_TOTAL int(5),
  ID_ALLOW int(5),
  ID_CATE varchar(5),
  PRICE decimal(5,3),
  CREATE_DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE_TIME timestamp NULL,
  PRIMARY KEY (TASK_NAME,BACKGROUND_NO)  
)  DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS BEST_TASK;  
CREATE TABLE BEST_TASK (  
  TASK_SORT int(1) NOT NULL,
  TASK_NAME varchar(20) NOT NULL,  
  BACKGROUND_NO varchar(5) NOT NULL,  
  ID_CATE varchar(5),
  PRICE decimal(5,3),
  UPDATE_DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TASK_SORT)  
)  DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS CURRENT_TASK_INDEX;  
CREATE TABLE CURRENT_TASK_INDEX (  
  USER_ID varchar(10) NOT NULL, 
  TASK_NAME varchar(20) NOT NULL,  
  START_DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (USER_ID)  
)  DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS TASK_EXEC_RECORD;  
CREATE TABLE TASK_EXEC_RECORD (  
  TASK_NAME varchar(20) NOT NULL,  
  USER_ID varchar(10) NOT NULL,  
  START_DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP,  
  STOP_DATE_TIME timestamp NULL,  
  PRIMARY KEY (TASK_NAME,USER_ID,START_DATE_TIME)  
)  DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS TASK_REWARD;  
CREATE TABLE TASK_REWARD (  
  TASK_NAME varchar(20) NOT NULL,  
  BACKGROUND_NO varchar(5) NOT NULL,
  USER_ID varchar(10) NOT NULL,  
  WORK_ID varchar(5) NOT NULL, 
  SUB_ID varchar(5) NOT NULL default 'non',
  QUANTITY int(6),  
  UPLOAD_DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (TASK_NAME,BACKGROUND_NO,USER_ID,WORK_ID,SUB_ID)  
)  DEFAULT CHARSET=utf8; 